public without sharing class ConstantClass {
    public Static Final String TaskSubjectForDuplicateLead = 'ReEnquiry Details';
    public Static Final String TaskSubjectForFollowUpLead = 'Take Followup with Lead';
    public Static Final String TaskSubjectForNewLead = 'New Lead Created, Please Reach Out!!!';
    public Static Final String errorForDuplicateLeadByPhone = 'Duplicate Lead by Phone Number!!!';
    public Static Final String errorForDuplicateLeadByEmail = 'Duplicate Lead by Email!!!';
    public Static Final String errorForPastFollowUpDate = 'Please fill Futuristic Date/Time !!!';
    
    
    public Static Final String TaskSubjectForConnectedCall = 'connect';
    public Static Final String TaskSubjectForCalledCall = 'call';
    
    public Static Final String LeadStageNewEnquiry = 'New Enquiry';
    public Static Final String LeadStageReEnquiry = 'ReEnquiry';
    public Static Final String LeadStageNotConnected = 'Not Connected';
    public Static Final String LeadStageConnected = 'Connected';
    public Static Final String LeadStageSVProspect = 'SV Prospect';
    public Static Final String LeadStageSVPlanned = 'SV Planned';
    public Static Final String LeadStageDrop = 'Drop';
    public Static Final String LeadStageConverted = 'Converted';
    
    
}