/**
* @author Aakash Jain
* @email aakash.jain@utilitarianlab.com
* @create date 19-05-2023 13:06:03
* @modify date 19-05-2023 13:06:03
* @desc [description]
*/

global without sharing class ResponseClass {
    
    global class ReponseWrapperforMB{
        global string status;
        global string success_code;
        global string success_message;
        global string error_code;
        global string error_message;
        global string lead_id;
    }
    
    global class ReponseWrapperforNintyNineAcres{
        global string status;
        global string success_code;
        global string success_message;
        global string error_code;
        global string error_message;
        global string lead_id;
    }
    global class ReponseWrapperforCommonFloor{
        global string status;
        global string success_code;
        global string success_message;
        global string error_code;
        global string error_message;
        global string lead_id;
    }

    global class ReponseWrapperforWebsiteLeadCreation{
        global string status;
        global string success_code;
        global string success_message;
        global string error_code;
        global string error_message;
        global string lead_id;
    }
}